### ISSUE TITLE
Four undefined names in Python code

### ISSUE THREAD

**Issue by cclauss** [yoyoyo-yo/Gasyori100knock#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/yoyoyo-yo/Gasyori100knock on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./Question_41_50/answer_48.py:44:23: F821 undefined name 'MF'
            if np.sum(MF * tmp[y-1:y+2, x-1:x+2]) < 255*4:
                      ^
./Question_01_10/answer_4.py:10:16: F821 undefined name 'r'
out = 0.2126 * r + 0.7152 * g + 0.0722 * b
               ^
./Question_01_10/answer_4.py:10:29: F821 undefined name 'g'
out = 0.2126 * r + 0.7152 * g + 0.0722 * b
                            ^
./Question_01_10/answer_4.py:10:42: F821 undefined name 'b'
out = 0.2126 * r + 0.7152 * g + 0.0722 * b
                                         ^
4     F821 undefined name 'r'
4
```

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by yoyoyo-yo** [comment]
Many thanks!
I fixed.
