### ISSUE TITLE
Q.9. ガウシアンフィルタ の解答コードについて

### ISSUE THREAD

**Issue by kokosabu** [yoyoyo-yo/Gasyori100knock#11]
フィルタの入力も出力も同じoutを使用しているので、フィルタ処理する際に、フィルタ後の画素データを使っている事になります。これは意図した処理と異なると思います。

```python
 26 for y in range(H):
 27     for x in range(W):
 28         for c in range(C):
 29             out[pad+y, pad+x, c] = np.sum(K * out[y:y+K_size, x:x+K_size, c])
```

out[1, 1, 0] = np.sum(K * out[0:3, 0:3, 0])
…
out[2, 2, 0] = np.sum(K * out[1:4, 1:4, 0]) ← out[1, 1]はフィルタ済み

**Comment by yoyoyo-yo** [comment]
ありがとうございます！　見逃してました
