### ISSUE TITLE
about Chinese

### ISSUE THREAD

**Issue by pureyb** [yoyoyo-yo/Gasyori100knock#13]
Dear author, hello, I am very interested in this content, but could you please provide a Chinese version of Chinese character recognition? Thank you very much

**Comment by yoyoyo-yo** [comment]
Hi! Thanks for your reaction.
Do you mean that any example to recognize Chinese character?
If you know opensource for them, please tell me!

If you are interested in deep learning, i am creating deep learning problems >> https://github.com/yoyoyo-yo/DeepLearningMugenKnock
Please refer!

**Comment by kokosabu** [comment]
Hi!
I guess this repository is a Chinese version.
https://github.com/gzr2017/ImageProcessing100Wen

@shinebo @yoyoyo-yo @gzr2017

**Comment by zhouchiji** [comment]
@yoyoyo-yo Hi! your twitter address is missing, I can't find you on twitter

**Comment by yoyoyo-yo** [comment]
@zhouchiji Oh, sorry... I fixed README.md link

**Comment by pureyb** [comment]
> 嗨！
> 我猜这个存储库是中文版本。
> https://github.com/gzr2017/ImageProcessing100Wen
> 
> @shinebo @ yoyoyo-yo @ gzr2017

ok, thank you very much, that is interest
