### ISSUE TITLE
Qustion 67 HOG(Step.2) 勾配ヒストグラムについて

### ISSUE THREAD

**Issue by kjmatu** [yoyoyo-yo/Gasyori100knock#35]
解答のコードを見ると38行目の最後ヒストグラムに代入している際のgra_nとmagの配列のインデックスに突然4という数字が現れており混乱しております。
https://github.com/yoyoyo-yo/Gasyori100knock/blob/a5fb794556e8faf9584934bf5438183cd9d40550/Question_61_70/answers/answer_67.py#L38
推測では、このインデックスには元画像の位置を表すインデックスがくると思っているのですがいかかでしょうか？
```python
Hist[y, x, gra_n[y*N+j, x*N+i]] += mag[y*N+j, x*N+i]
```
私の推測間違いであれば申し訳ありません。

**Comment by Ivan-wang** [comment]
Same question. There seems to be an overlap between cells when using `4`. But I reviewed some blogs about HOG, none of them mentioned the overlap between cells. Also when using `4`, the bottom right parts of the magnitude values cannot be covered.

**Comment by yoyoyo-yo** [comment]
Thank you!
I forget to fix from 4 to 8. 

ありがとうございます。4から8に直すのを忘れていました。
