### ISSUE TITLE
NameError: name 'img3' is not defined

### ISSUE THREAD

**Issue by KuKuXia** [yoyoyo-yo/Gasyori100knock#4]
The problem occurred in the Tutorial/README.md files. In the last practice part:
Original Code:
```bash
>>> import cv2
>>> img = cv2.imread ( " imori.jpg " )
>>> H, W, C = img.shape
>>> img [: H // 2,: W // 2] = img [: H // 2,: W // 2, (2, 1, 0)]
>>> cv2.imshow ( ' ' , img3) ; cv2.waitKey (0)
```

Solution:
```bash
>>> import cv2
>>> img = cv2.imread("./assets/imori.jpg")
>>> img3 = img.copy()   # make a copy of the img
>>> H, W, C = img3.shape
>>> img3[:H//2, :W//2] = img3[:H//2, :W//2, (2, 1, 0)]
>>> cv2.imshow('', img3); cv2.waitKey(0)
```
Thanks for your effort, yoyoyo-yo. I'm interested in CV and AI. Your repo is awesome, so I've forked your repo to learn and try to translate it into English now. I typed each code again to make sure it would work on my machine. Hope this could help other people and thank you again. 
The English version of your repo is [here](https://github.com/KuKuXia/Image_Processing_100_Questions).

**Comment by yoyoyo-yo** [comment]
Many thanks!!  I fixed.
Your translation is very helpful, so I really appreciate u!!
I introduce your translation.

**Comment by KuKuXia** [comment]
@yoyoyo-yo Thanks for your introduce. Wish we could make it better, together. 👍
