### ISSUE TITLE
補間(Q.26・Q.27)の説明における重みの扱いが不適切に見える

### ISSUE THREAD

**Issue by mikecat** [yoyoyo-yo/Gasyori100knock#44]
Q.26. Bi-linear補間 において、
3で計算したwがその後の説明で使われておらず、混乱を招きそうに思えます。

また、Q.27. Bi-cubic補間 において、
定義したh(t)がその後の説明で使われていない上に、
定義されていないwxiおよびwyjが使われており、混乱しました。

**Comment by yoyoyo-yo** [comment]
修正しました
