### ISSUE TITLE
Q.30. アフィン変換(回転) において、画像全体を見れていない

### ISSUE THREAD

**Issue by mikecat** [yoyoyo-yo/Gasyori100knock#45]
Q.30. アフィン変換(回転) の(2)において、
「反時計方向に30度回転した画像全体を見れる画像を作成せよ」
という問題であるにもかかわらず、
提示されている出力では回転した画像の四隅が切れており、全体を見れないと思います。

**Comment by yoyoyo-yo** [comment]
ありがとうございます！　修正しました
