### ISSUE TITLE
Cannyエッジ検出(Q.41・Q.43)が不適切と考えられる

### ISSUE THREAD

**Issue by mikecat** [yoyoyo-yo/Gasyori100knock#46]
# 勾配強度(Q.41)の問題

勾配強度として提示されている出力を見ると、白い場所の中に不自然に黒い場所があります。
これは整数ラップアラウンドによるものと予測でき、不適切な可能性が考えられます。
参考として、例えばfxもfyも255のとき、edgeはおよそ255*1.4になり、255をオーバーします。

# 勾配角度(Q.41)の問題

Pythonの実装において、勾配角度はnumpyのarctan関数を用いて計算しているようです。
[numpy.arctan — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctan.html)
この関数の(実部の)値域は[-pi/2, pi/2]、すなわちおよそ-1.6～1.6です。
にもかかわらず、勾配角度の量子化の定義ではこの範囲を超える±2.4142という値が用いられており、
不自然であると考えられます。

# 閾値処理(Q.43)の問題

閾値処理の説明文において、edge(x,y)が
「HTより大きい場合」「LTより小さい場合」「LT < edge(x,y) < HTの時」
の定義は書かれていますが、edge(x,y)=HTおよびedge(x,y)=LTのときの処理が書かれておらず、
混乱を招くと考えられます。

**Comment by yoyoyo-yo** [comment]
ありがとうございます！

Q.41はたしかに場合分けがおかしかったので修正しました
Q.43についても修正しました
