### ISSUE TITLE
Q.44. Hough変換・直線検出 (Step.1) Hough変換 の表の範囲が不適切な可能性

### ISSUE THREAD

**Issue by mikecat** [yoyoyo-yo/Gasyori100knock#47]
Q.44. Hough変換・直線検出 (Step.1) Hough変換 において、
縦幅rmaxの表を用いて処理を行っています。
しかし、度数法の角度tが0～179の値をとるとき、
r = x * cos(t) + y * sin(t) は負の値になることがあります。
rが負の値のとき、本来表の上側にプロットするべき点が、
Pythonの仕様によりラップアラウンドされて表の下側に来ているようです。
これは不適切な可能性が考えられます。

比較として、例えば
[Hough変換による画像からの直線や円の検出：CodeZine（コードジン）](https://codezine.jp/article/detail/153)
に掲載されているプログラムでは、-rmax～rmaxに近い長さの表を確保しているようです。

**Comment by yoyoyo-yo** [comment]
ありがとうございます！
アルゴリズムとpythonの解答を修正しました！
