### ISSUE TITLE
Q.36. JPEG圧縮 (Step.1)離散コサイン変換 の説明が不適切

### ISSUE THREAD

**Issue by mikecat** [yoyoyo-yo/Gasyori100knock#48]
Q.36. JPEG圧縮 (Step.1)離散コサイン変換 において、
定義が書かれていないC(u)、C(v)、C(x)、C(y)が使われており、混乱のもとになります。

また、コードや以下の他サイトを参考にすると、
C(u) = 1/sqrt(2) (u=0), 1 (u≒0) であると予想できますが、
ここで書かれている定義式では、Cの引数がDCT、IDCTともに出力側の添字になっています。
しかし、他サイトでは、IDCTにおけるCの引数(または相当するもの)は、
入力側の添字になっています。
さらに、ここのコードもIDCTにおけるCの引数を入力側の添字とするものになっています。
したがって、このIDCTにおけるCの引数を出力側の添字にする定義式は不適切と考えられます。

他サイト(の例)

* [離散コサイン変換 - Wikipedia](https://ja.wikipedia.org/wiki/%E9%9B%A2%E6%95%A3%E3%82%B3%E3%82%B5%E3%82%A4%E3%83%B3%E5%A4%89%E6%8F%9B)
* [離散コサイン変換 : kei@sodan](http://funini.com/kei/math/dct.shtml)
* [もりとにーのブログ: 離散コサイン変換(DCT)をPythonで実装した[Python]](https://tony-mooori.blogspot.com/2016/02/dctpythonpython.html)

**Comment by yoyoyo-yo** [comment]
修正しました
