### ISSUE TITLE
Q.57 ZNCCによるテンプレートマッチングについて

### ISSUE THREAD

**Issue by N-Hirahara** [yoyoyo-yo/Gasyori100knock#49]
Q.57 のZNCCを類似度として用いたパターンマッチングなのですが，解答では
```
mi = np.mean(img)
mt = np.mean(temp)
```
として全体画像及びテンプレート画像の平均をZNCCの計算に用いていましたが，
ここでは各チャンネルごとの平均値を用いるべきなのではないでしょうか？
例えば，
```
mi = np.mean(img, axis=(0,1), keepdims=True)
mt = np.mean(temp, axis=(0,1), keepdims=True)
```
のように全体画像とテンプレート画像のRGBチャンネルごとにおける平均値を計算し，これらをZNCCの算出に用いたところ，
前問までのパターンマッチング手法と同じような正しい検出が行われました．

見当違いの意見でしたら申し訳ありません．ご検討の方よろしくお願いします．

**Comment by yoyoyo-yo** [comment]
ありがとうございます！　修正しました
