### ISSUE TITLE
Question 68 ignored channels

### ISSUE THREAD

**Issue by Frigidity-savvy** [yoyoyo-yo/Gasyori100knock#51]
Each descriptor has 9 channels however codes below just sum all of them as an integrity.
Hist[y, x] /= np.sqrt(np.sum(Hist[max(y-1,0):min(y+2, HH), max(x-1,0):min(x+2, HW)] ** 2) + eps)

**Comment by yoyoyo-yo** [comment]
@Frigidity-savvy Thank you! I will fix
