### ISSUE TITLE
Q.41. 解答でガウシアンフィルタが無視されている

### ISSUE THREAD

**Issue by sensen963** [yoyoyo-yo/Gasyori100knock#56]
Q41の解答にてSobelフィルタを作用させる際に仮引数imgではなくgrayをコピーしてしまっています．そのためガウシアンフィルタを作用させていないグレイスケール画像を呼び出して使用されているように見えます．
https://github.com/yoyoyo-yo/Gasyori100knock/blob/31113f1222b72d4dff3adf29535521695fcb57cc/Question_41_50/answers_py/answer_41.py#L66

**Comment by yoyoyo-yo** [comment]
ありがとうございます！　なんか変な感じだった原因がわかりました笑
とても助かりました！！
