### ISSUE TITLE
Question 26 bug

### ISSUE THREAD

**Issue by Hu-chi** [yoyoyo-yo/Gasyori100knock#59]
I don't think this can be accepted on one image where its height != width 
https://github.com/yoyoyo-yo/Gasyori100knock/blob/df2c5223ea49aff396f8449f07811b0460bd97c4/Question_21_30/answers_py/answer_26.py#L14

This is my version:
```python
height, width = img.shape[:2]
height_t = int(height * proportion)
width_t = int(width * proportion)
y = np.arange(height_t).repeat(width_t).reshape(height_t, -1)
```

I learn a lot from your code. But here I hold different opinions on reshape size.

**Comment by yoyoyo-yo** [comment]
Thanks! This also be pointed and I fixed
