### ISSUE TITLE
Question5 HSV>RGB変換について

### ISSUE THREAD

**Issue by Meowhal** [yoyoyo-yo/Gasyori100knock#6]
answer_5.py 36行目でHに対して切り捨て除算を行っていますが、
これではHが6種類しかない画像になってしまいませんか？

この分野はあまり詳しくないので当方の勘違いかもしれませんが、ご確認お願いします。

**Comment by yoyoyo-yo** [comment]
ありがとうございます！
ご指摘の通り H // 60 でなく H / 60が正答でした。（修正済み）

**Comment by Meowhal** [comment]
対応ありがとうございます:blush:
