### ISSUE TITLE
Question13 bug

### ISSUE THREAD

**Issue by Zpadger** [yoyoyo-yo/Gasyori100knock#62]
Hello，when I running the anwser_13.py,there is an error:“ValueError：not enough values to unpack (expected 3 got 2)”,the wrong code "H, W, C = img.shape" needs to change as "H, W= img.shape" thank you!
`# max-min filter
def max_min_filter(img, K_size=3):
	H, W, C = img.shape`
`# max-min filter
def max_min_filter(img, K_size=3):
	H, W= img.shape`

**Comment by yoyoyo-yo** [comment]
Thanks! I fixed
