### ISSUE TITLE
anwser_16.py&anwser_17.py bug

### ISSUE THREAD

**Issue by Zpadger** [yoyoyo-yo/Gasyori100knock#65]
Hello,when I run the code anwser_16.py and anwser_17.py,there is a question:
`Traceback (most recent call last):
  File "/home/zpj/PycharmProjects/ObjectDetection/Question_100/Q17_LaplacianFilter.py", line 52, in <module>
    out = laplacian_filter(gray, K_size=3)
  File "/home/zpj/PycharmProjects/ObjectDetection/Question_100/Q17_LaplacianFilter.py", line 19, in laplacian_filter
    H, W, C = img.shape
ValueError: not enough values to unpack (expected 3, got 2)`
My suggestion is that using 
`    if len(img.shape) == 3:
        H, W, C = img.shape
    else:
        img = np.expand_dims(img, axis=-1)
        H, W, C = img.shape`
replace
`H, W, C = img.shape`.

But I see your anwser_13.py already used
`if len(img.shape) == 3:
		H, W, C = img.shape

		## Zero padding
		pad = K_size // 2
		out = np.zeros((H + pad * 2, W + pad * 2, 3), dtype=np.float)
		out[pad: pad + H, pad: pad + W] = gray.copy().astype(np.float)
		tmp = out.copy()

		# filtering
		for y in range(H):
			for x in range(W):
				for c in range(3):
					out[pad + y, pad + x, c] = np.max(tmp[y: y + K_size, x: x + K_size, c]) - np.min(tmp[y: y + K_size, x: x + K_size, c])

		out = out[pad: pad + H, pad: pad + W].astype(np.uint8)

	else:
		H, W = img.shape

		## Zero padding
		pad = K_size // 2
		out = np.zeros((H + pad * 2, W + pad * 2), dtype=np.float)
		out[pad: pad + H, pad: pad + W] = gray.copy().astype(np.float)
		tmp = out.copy()

		# filtering
		for y in range(H):
			for x in range(W):
				out[pad + y, pad + x] = np.max(tmp[y: y + K_size, x: x + K_size]) - np.min(tmp[y: y + K_size, x: x + K_size])

		out = out[pad: pad + H, pad: pad + W].astype(np.uint8)
`
Could you tell me why and the difference between anwser_13.py and anwser_16.py? Thank you very much!

**Comment by yoyoyo-yo** [comment]
Thank you for your opinion! I fixed
