### ISSUE TITLE
Q.4. 大津の二値化の誤記

### ISSUE THREAD

**Issue by AkihiroSasabe** [yoyoyo-yo/Gasyori100knock#82]
素晴らしい教材を作成していただき、どうもありがとうございます。
誤記を2点、見つけましたのでご報告させていただきます。

Q.4. 大津の二値化のクラス間分散の式が
Sb^2 = w0(M0-Mt)^2 + w1(M1-Mt)^2
= w0w1(M0-Mt)^2
となっておりますが、最後の式は
w0w1(M0-M1)^2
だと思います。

また、分離度Xはクラス間分散÷クラス内分散なので、
X  = Sb^2 / Sb^2
ではなく、
X  = Sb^2 / Sw^2
だと思います。

細かいですが、ご確認何卒お願いします。

**Comment by yoyoyo-yo** [comment]
ありがとうございます！　大津の二値化だいぶ修正しました
