### ISSUE TITLE
イモリの画像が保存場所で異なる画像になっている。

### ISSUE THREAD

**Issue by yakataN** [yoyoyo-yo/Gasyori100knock#86]
イモリの画像が保存場所によって異なっています。具体的には以下の2つの画像が異なることを確認しています

- https://github.com/yoyoyo-yo/Gasyori100knock/raw/master/Question_01_10/imori.jpg
- https://github.com/yoyoyo-yo/Gasyori100knock/raw/master/assets/imori_128x128.png

以下は検証したコードとエラーログです。

コード

```python
from skimage import io

img1 = io.imread("https://github.com/yoyoyo-yo/Gasyori100knock/raw/master/Question_01_10/imori.jpg")
img2 = io.imread("https://github.com/yoyoyo-yo/Gasyori100knock/raw/master/assets/imori_128x128.png")

assert (img1 == img1).all(), "異なる画像です"
# ↓でerrorがthrowされる
assert (img1 == img2).all(), "異なる画像です"
```

error log

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-81-90a18587e37c> in <module>()
      6 assert (img1 == img1).all(), "異なる画像です"
      7 # ↓でerrorがthrowされる
----> 8 assert (img1 == img2).all(), "異なる画像です"

AssertionError: 異なる画像です
```

**Comment by yoyoyo-yo** [comment]
コメントありがとうございます
たしかに画像は違います。
これは拡張子がjpg, pngによる違いです。jpgでは圧縮が行われていて、画像の見た目は変わっていない様に見えまっすが、画素値が若干違っています。pngの方がそのような圧縮はないため、オリジナルに近い画素値であり、画像の容量も若干大きいです

なので(img1 == im2).all() をすると、画素値が違うのでエラーをはきます。
このような理由もあって、この中の問題を解く時はpngを使うことを推奨しています

**Comment by yakataN** [comment]
拡張子違うの見逃してました。すいません。本Issueは閉じさせてもらいます。
