### ISSUE TITLE
Question.14 の解答のコードおよび画像について

### ISSUE THREAD

**Issue by optie-f** [yoyoyo-yo/Gasyori100knock#9]
Q.14 の微分フィルタについてなのですが、解答のコードでは

```python
out = out[pad:pad+H, pad:pad+W].astype(np.uint8)
```
となっていますが、このように numpy で uint8 に変換すると、小数点を切り捨てたのちに 256 の剰余が取られるため、負の値については正しくない結果になっていると思われます。例えば、前後に print を噛ませると

```python
print(np.max(out),np.min(out)) # 21.8888888889 -13.1111111111
out = out[pad:pad+H, pad:pad+W].astype(np.uint8)
print(np.max(out),np.min(out) # 255 0
```

のようになります。

おそらく正確には、絶対値を取るか負の値を 0 にクリッピングしてから uint8 に変換すべきものと思われますが、いかがでしょうか。

**Comment by yoyoyo-yo** [comment]
ありがとうございます！！　ご指摘のとおりでした。
ここでは[0,255]の範囲にクリッピングして修正しました。
