### ISSUE TITLE
about code_16 : sobel

### ISSUE THREAD

**Issue by IRVING-L** [yoyoyo-yo/Gasyori100knock#91]
when we use Sobel operator to calculate the gradient value of I(x,y) at a certain point, when the calculated value exceeds 255(unit8), I can see that you use the fmin() function. But will this not lead to the lack of discrimination for values higher than 255?

**Comment by yoyoyo-yo** [comment]
@IRVING-L Thank you for your reaction.

I fixed to use normalize in sobel.

I don't understand your problem accurately, but normalization may solve the difference of values higher than 255.
