### ISSUE TITLE
Q15 prewitt filter の重みが画像と実装でことなる

### ISSUE THREAD

**Issue by SkiMsyk** [yoyoyo-yo/Gasyori100knock#95]
![image](https://user-images.githubusercontent.com/46867978/107866639-470bf000-6eb6-11eb-8dd0-bf9161d84a4e.png)

上記の部分が実装では下記のようになっていますが、画像が間違っているようですので修正いただけると助かります。

```python
## prewitt vertical kernel
Kv = [[-1., -1., -1.],[0., 0., 0.], [1., 1., 1.]]
## prewitt horizontal kernel
Kh = [[-1., 0., 1.],[-1., 0., 1.],[-1., 0., 1.]]
```

**Comment by yoyoyo-yo** [comment]
@SkiMsyk ありがとうございます！

本日、ノック全体を修正し、Prewittもそれにともなって修正しました。

よろしければ、新しいものでご確認頂ければと思います。よろしくお願い致します。
